// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: BusStop852

#ifndef _BUSSTOP852_UI_H
#define _BUSSTOP852_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_ScreenBoot.h"
#include "ui_ScreenMain.h"
#include "ui_ScreenDetail.h"
#include "ui_ScreenSystem.h"
#include "ui_ScreenAlarm.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// FONTS
LV_FONT_DECLARE( ui_font_NotoSansTC);
LV_FONT_DECLARE( ui_font_NotoSansTC_12);
LV_FONT_DECLARE( ui_font_NotoSansTC_14);
LV_FONT_DECLARE( ui_font_NotoSansTC_20);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
