// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: BusStop852

#ifndef UI_SCREENBOOT_H
#define UI_SCREENBOOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenBoot
extern void ui_ScreenBoot_screen_init(void);
extern void ui_ScreenBoot_screen_destroy(void);
extern void ui_event_ScreenBoot( lv_event_t * e);
extern lv_obj_t *ui_ScreenBoot;
extern lv_obj_t *ui_SystemTitleLabel;
extern lv_obj_t *ui_BootStatusLabel;
extern lv_obj_t *ui_Spinner1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

