// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: BusStop852

#ifndef UI_SCREENALARM_H
#define UI_SCREENALARM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenAlarm
extern void ui_ScreenAlarm_screen_init(void);
extern void ui_ScreenAlarm_screen_destroy(void);
extern lv_obj_t *ui_ScreenAlarm;
extern lv_obj_t *ui_AlarmHeader;
extern void ui_event_BtnAlarmBack( lv_event_t * e);
extern lv_obj_t *ui_BtnAlarmBack;
extern lv_obj_t *ui_BtnAlarmBackLabel;
extern lv_obj_t *ui_AlarmTitleLabel;
extern lv_obj_t *ui_AlarmSubtitle;
extern lv_obj_t *ui_RollerHour;
extern lv_obj_t *ui_RollerMinute;
extern lv_obj_t *ui_SwitchLabel;
extern lv_obj_t *ui_SwitchAlarmActive;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

