// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: BusStop852

#include "ui.h"

lv_obj_t *ui_ScreenAlarm = NULL;lv_obj_t *ui_AlarmHeader = NULL;lv_obj_t *ui_BtnAlarmBack = NULL;lv_obj_t *ui_BtnAlarmBackLabel = NULL;lv_obj_t *ui_AlarmTitleLabel = NULL;lv_obj_t *ui_AlarmSubtitle = NULL;lv_obj_t *ui_RollerHour = NULL;lv_obj_t *ui_RollerMinute = NULL;lv_obj_t *ui_SwitchLabel = NULL;lv_obj_t *ui_SwitchAlarmActive = NULL;
// event funtions
void ui_event_BtnAlarmBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_ScreenMain_screen_init);
}
}

// build funtions

void ui_ScreenAlarm_screen_init(void)
{
ui_ScreenAlarm = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScreenAlarm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenAlarm, lv_color_hex(0xF8F9FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenAlarm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AlarmHeader = lv_obj_create(ui_ScreenAlarm);
lv_obj_set_width( ui_AlarmHeader, 320);
lv_obj_set_height( ui_AlarmHeader, 36);
lv_obj_remove_flag( ui_AlarmHeader, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AlarmHeader, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AlarmHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnAlarmBack = lv_button_create(ui_AlarmHeader);
lv_obj_set_width( ui_BtnAlarmBack, 40);
lv_obj_set_height( ui_BtnAlarmBack, 24);
lv_obj_set_x( ui_BtnAlarmBack, 8 );
lv_obj_set_y( ui_BtnAlarmBack, 0 );
lv_obj_set_align( ui_BtnAlarmBack, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_BtnAlarmBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnAlarmBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BtnAlarmBackLabel = lv_label_create(ui_BtnAlarmBack);
lv_obj_set_width( ui_BtnAlarmBackLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnAlarmBackLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BtnAlarmBackLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BtnAlarmBackLabel,"<");

ui_AlarmTitleLabel = lv_label_create(ui_AlarmHeader);
lv_obj_set_width( ui_AlarmTitleLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AlarmTitleLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_AlarmTitleLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_AlarmTitleLabel,"Departure Alarm");
lv_obj_set_style_text_color(ui_AlarmTitleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AlarmTitleLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AlarmSubtitle = lv_label_create(ui_ScreenAlarm);
lv_obj_set_width( ui_AlarmSubtitle, 200);
lv_obj_set_height( ui_AlarmSubtitle, 20);
lv_obj_set_x( ui_AlarmSubtitle, 0 );
lv_obj_set_y( ui_AlarmSubtitle, 55 );
lv_obj_set_align( ui_AlarmSubtitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_AlarmSubtitle,"SET TARGET LEAVE TIME");
lv_obj_set_style_text_color(ui_AlarmSubtitle, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AlarmSubtitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AlarmSubtitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AlarmSubtitle, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RollerHour = lv_roller_create(ui_ScreenAlarm);
lv_roller_set_options( ui_RollerHour, "06\\\n07\\\n08\\\n09\\\n10\\\n11\\\n12", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_RollerHour, 50);
lv_obj_set_height( ui_RollerHour, 80);
lv_obj_set_x( ui_RollerHour, -40 );
lv_obj_set_y( ui_RollerHour, -10 );
lv_obj_set_align( ui_RollerHour, LV_ALIGN_CENTER );

ui_RollerMinute = lv_roller_create(ui_ScreenAlarm);
lv_roller_set_options( ui_RollerMinute, "00\\\n05\\\n10\\\n15\\\n20\\\n25\\\n30\\\n35\\\n40\\\n45\\\n50\\\n55", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_RollerMinute, 50);
lv_obj_set_height( ui_RollerMinute, 80);
lv_obj_set_x( ui_RollerMinute, 40 );
lv_obj_set_y( ui_RollerMinute, -10 );
lv_obj_set_align( ui_RollerMinute, LV_ALIGN_CENTER );

ui_SwitchLabel = lv_label_create(ui_ScreenAlarm);
lv_obj_set_width( ui_SwitchLabel, 180);
lv_obj_set_height( ui_SwitchLabel, 15);
lv_obj_set_x( ui_SwitchLabel, 0 );
lv_obj_set_y( ui_SwitchLabel, -55 );
lv_obj_set_align( ui_SwitchLabel, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_SwitchLabel,"ENABLE LIVE TRACKING");
lv_obj_set_style_text_align(ui_SwitchLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SwitchLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SwitchAlarmActive = lv_switch_create(ui_ScreenAlarm);
lv_obj_set_width( ui_SwitchAlarmActive, 60);
lv_obj_set_height( ui_SwitchAlarmActive, 25);
lv_obj_set_x( ui_SwitchAlarmActive, 0 );
lv_obj_set_y( ui_SwitchAlarmActive, -25 );
lv_obj_set_align( ui_SwitchAlarmActive, LV_ALIGN_BOTTOM_MID );

lv_obj_add_event_cb(ui_BtnAlarmBack, ui_event_BtnAlarmBack, LV_EVENT_ALL, NULL);

}

void ui_ScreenAlarm_screen_destroy(void)
{
   if (ui_ScreenAlarm) lv_obj_del(ui_ScreenAlarm);

// NULL screen variables
ui_ScreenAlarm= NULL;
ui_AlarmHeader= NULL;
ui_BtnAlarmBack= NULL;
ui_BtnAlarmBackLabel= NULL;
ui_AlarmTitleLabel= NULL;
ui_AlarmSubtitle= NULL;
ui_RollerHour= NULL;
ui_RollerMinute= NULL;
ui_SwitchLabel= NULL;
ui_SwitchAlarmActive= NULL;

}
