// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: BusStop852

#include "ui.h"

lv_obj_t *ui_ScreenDetail = NULL;lv_obj_t *ui_DetailHeader = NULL;lv_obj_t *ui_BtnBack = NULL;lv_obj_t *ui_BtnBackLabel = NULL;lv_obj_t *ui_DetailTitleLabel = NULL;lv_obj_t *ui_TimelineLine = NULL;lv_obj_t *ui_NodeStop1 = NULL;lv_obj_t *ui_StopStationLabel1 = NULL;lv_obj_t *ui_StopETALabel1 = NULL;lv_obj_t *ui_NodeStop2 = NULL;lv_obj_t *ui_StopStationLabel2 = NULL;lv_obj_t *ui_StopETALabel2 = NULL;lv_obj_t *ui_NodeStop3 = NULL;lv_obj_t *ui_StopStationLabel3 = NULL;lv_obj_t *ui_StopETALabel3 = NULL;
// event funtions
void ui_event_BtnBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_ScreenMain_screen_init);
}
}

// build funtions

void ui_ScreenDetail_screen_init(void)
{
ui_ScreenDetail = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScreenDetail, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenDetail, lv_color_hex(0xF8F9FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenDetail, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DetailHeader = lv_obj_create(ui_ScreenDetail);
lv_obj_set_width( ui_DetailHeader, 320);
lv_obj_set_height( ui_DetailHeader, 36);
lv_obj_remove_flag( ui_DetailHeader, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_DetailHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DetailHeader, lv_color_hex(0xE1251B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DetailHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DetailHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DetailHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DetailHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DetailHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_DetailHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_DetailHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnBack = lv_button_create(ui_DetailHeader);
lv_obj_set_width( ui_BtnBack, 40);
lv_obj_set_height( ui_BtnBack, 24);
lv_obj_set_x( ui_BtnBack, 8 );
lv_obj_set_y( ui_BtnBack, 0 );
lv_obj_set_align( ui_BtnBack, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_BtnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnBack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnBackLabel = lv_label_create(ui_BtnBack);
lv_obj_set_width( ui_BtnBackLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnBackLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BtnBackLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BtnBackLabel,"<");

ui_DetailTitleLabel = lv_label_create(ui_DetailHeader);
lv_obj_set_width( ui_DetailTitleLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DetailTitleLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_DetailTitleLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DetailTitleLabel,"Route 2A Timeline");
lv_obj_set_style_text_color(ui_DetailTitleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DetailTitleLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DetailTitleLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimelineLine = lv_obj_create(ui_ScreenDetail);
lv_obj_set_width( ui_TimelineLine, 4);
lv_obj_set_height( ui_TimelineLine, 160);
lv_obj_set_x( ui_TimelineLine, 25 );
lv_obj_set_y( ui_TimelineLine, 55 );
lv_obj_remove_flag( ui_TimelineLine, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TimelineLine, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TimelineLine, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TimelineLine, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NodeStop1 = lv_obj_create(ui_ScreenDetail);
lv_obj_set_width( ui_NodeStop1, 10);
lv_obj_set_height( ui_NodeStop1, 10);
lv_obj_set_x( ui_NodeStop1, 22 );
lv_obj_set_y( ui_NodeStop1, 65 );
lv_obj_remove_flag( ui_NodeStop1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_NodeStop1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_NodeStop1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NodeStop1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_NodeStop1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_NodeStop1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StopStationLabel1 = lv_label_create(ui_ScreenDetail);
lv_obj_set_width( ui_StopStationLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StopStationLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StopStationLabel1, 42 );
lv_obj_set_y( ui_StopStationLabel1, 62 );
lv_label_set_text(ui_StopStationLabel1,"淘大花園 (Amoy Gardens)");
lv_obj_set_style_text_color(ui_StopStationLabel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_StopStationLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_StopStationLabel1, &ui_font_NotoSansTC_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StopETALabel1 = lv_label_create(ui_ScreenDetail);
lv_obj_set_width( ui_StopETALabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StopETALabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StopETALabel1, -15 );
lv_obj_set_y( ui_StopETALabel1, 62 );
lv_obj_set_align( ui_StopETALabel1, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_StopETALabel1,"4 min");
lv_obj_set_style_text_color(ui_StopETALabel1, lv_color_hex(0xE1251B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_StopETALabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_StopETALabel1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NodeStop2 = lv_obj_create(ui_ScreenDetail);
lv_obj_set_width( ui_NodeStop2, 10);
lv_obj_set_height( ui_NodeStop2, 10);
lv_obj_set_x( ui_NodeStop2, 22 );
lv_obj_set_y( ui_NodeStop2, 115 );
lv_obj_remove_flag( ui_NodeStop2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_NodeStop2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_NodeStop2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NodeStop2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_NodeStop2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_NodeStop2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StopStationLabel2 = lv_label_create(ui_ScreenDetail);
lv_obj_set_width( ui_StopStationLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StopStationLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StopStationLabel2, 42 );
lv_obj_set_y( ui_StopStationLabel2, 112 );
lv_label_set_text(ui_StopStationLabel2,"振華苑 (Chun Wah Court)");
lv_obj_set_style_text_color(ui_StopStationLabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_StopStationLabel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_StopStationLabel2, &ui_font_NotoSansTC_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StopETALabel2 = lv_label_create(ui_ScreenDetail);
lv_obj_set_width( ui_StopETALabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StopETALabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StopETALabel2, -15 );
lv_obj_set_y( ui_StopETALabel2, 112 );
lv_obj_set_align( ui_StopETALabel2, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_StopETALabel2,"6 min");
lv_obj_set_style_text_color(ui_StopETALabel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_StopETALabel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_StopETALabel2, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NodeStop3 = lv_obj_create(ui_ScreenDetail);
lv_obj_set_width( ui_NodeStop3, 10);
lv_obj_set_height( ui_NodeStop3, 10);
lv_obj_set_x( ui_NodeStop3, 22 );
lv_obj_set_y( ui_NodeStop3, 165 );
lv_obj_remove_flag( ui_NodeStop3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_NodeStop3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_NodeStop3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_NodeStop3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_NodeStop3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_NodeStop3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StopStationLabel3 = lv_label_create(ui_ScreenDetail);
lv_obj_set_width( ui_StopStationLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StopStationLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StopStationLabel3, 42 );
lv_obj_set_y( ui_StopStationLabel3, 162 );
lv_label_set_text(ui_StopStationLabel3,"樂雅苑 (Lok Nga Court)");
lv_obj_set_style_text_color(ui_StopStationLabel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_StopStationLabel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_StopStationLabel3, &ui_font_NotoSansTC_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StopETALabel3 = lv_label_create(ui_ScreenDetail);
lv_obj_set_width( ui_StopETALabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_StopETALabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_StopETALabel3, -15 );
lv_obj_set_y( ui_StopETALabel3, 162 );
lv_obj_set_align( ui_StopETALabel3, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_StopETALabel3,"11 min");
lv_obj_set_style_text_color(ui_StopETALabel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_StopETALabel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_StopETALabel3, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BtnBack, ui_event_BtnBack, LV_EVENT_ALL, NULL);

}

void ui_ScreenDetail_screen_destroy(void)
{
   if (ui_ScreenDetail) lv_obj_del(ui_ScreenDetail);

// NULL screen variables
ui_ScreenDetail= NULL;
ui_DetailHeader= NULL;
ui_BtnBack= NULL;
ui_BtnBackLabel= NULL;
ui_DetailTitleLabel= NULL;
ui_TimelineLine= NULL;
ui_NodeStop1= NULL;
ui_StopStationLabel1= NULL;
ui_StopETALabel1= NULL;
ui_NodeStop2= NULL;
ui_StopStationLabel2= NULL;
ui_StopETALabel2= NULL;
ui_NodeStop3= NULL;
ui_StopStationLabel3= NULL;
ui_StopETALabel3= NULL;

}
