// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: BusStop852

#ifndef UI_SCREENDETAIL_H
#define UI_SCREENDETAIL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenDetail
extern void ui_ScreenDetail_screen_init(void);
extern void ui_ScreenDetail_screen_destroy(void);
extern lv_obj_t *ui_ScreenDetail;
extern lv_obj_t *ui_DetailHeader;
extern void ui_event_BtnBack( lv_event_t * e);
extern lv_obj_t *ui_BtnBack;
extern lv_obj_t *ui_BtnBackLabel;
extern lv_obj_t *ui_DetailTitleLabel;
extern lv_obj_t *ui_TimelineLine;
extern lv_obj_t *ui_NodeStop1;
extern lv_obj_t *ui_StopStationLabel1;
extern lv_obj_t *ui_StopETALabel1;
extern lv_obj_t *ui_NodeStop2;
extern lv_obj_t *ui_StopStationLabel2;
extern lv_obj_t *ui_StopETALabel2;
extern lv_obj_t *ui_NodeStop3;
extern lv_obj_t *ui_StopStationLabel3;
extern lv_obj_t *ui_StopETALabel3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

