// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: BusStop852

#include "ui.h"

lv_obj_t *ui_ScreenSystem = NULL;lv_obj_t *ui_SystemHeader = NULL;lv_obj_t *ui_BtnSystemBack = NULL;lv_obj_t *ui_BtnSystemBackLabel = NULL;lv_obj_t *ui_SystemTitleLabel1 = NULL;lv_obj_t *ui_SysIPLabel = NULL;lv_obj_t *ui_SysAPIStatusLabel = NULL;lv_obj_t *ui_SysHeapLabel = NULL;lv_obj_t *ui_AlertNoticeBox = NULL;lv_obj_t *ui_AlertTextLabel = NULL;
// event funtions
void ui_event_BtnSystemBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenMain, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0, &ui_ScreenMain_screen_init);
}
}

// build funtions

void ui_ScreenSystem_screen_init(void)
{
ui_ScreenSystem = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScreenSystem, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenSystem, lv_color_hex(0xF8F9FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenSystem, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemHeader = lv_obj_create(ui_ScreenSystem);
lv_obj_set_width( ui_SystemHeader, 320);
lv_obj_set_height( ui_SystemHeader, 36);
lv_obj_remove_flag( ui_SystemHeader, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SystemHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SystemHeader, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SystemHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SystemHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SystemHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SystemHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SystemHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_SystemHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SystemHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnSystemBack = lv_button_create(ui_SystemHeader);
lv_obj_set_width( ui_BtnSystemBack, 40);
lv_obj_set_height( ui_BtnSystemBack, 24);
lv_obj_set_x( ui_BtnSystemBack, 8 );
lv_obj_set_y( ui_BtnSystemBack, 0 );
lv_obj_set_align( ui_BtnSystemBack, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_BtnSystemBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_BtnSystemBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnSystemBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnSystemBack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnSystemBackLabel = lv_label_create(ui_BtnSystemBack);
lv_obj_set_width( ui_BtnSystemBackLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnSystemBackLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BtnSystemBackLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BtnSystemBackLabel,"<");

ui_SystemTitleLabel1 = lv_label_create(ui_SystemHeader);
lv_obj_set_width( ui_SystemTitleLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SystemTitleLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SystemTitleLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SystemTitleLabel1,"System Monitor");
lv_obj_set_style_text_color(ui_SystemTitleLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SystemTitleLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SystemTitleLabel1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SysIPLabel = lv_label_create(ui_ScreenSystem);
lv_obj_set_width( ui_SysIPLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SysIPLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SysIPLabel, 20 );
lv_obj_set_y( ui_SysIPLabel, 55 );
lv_label_set_text(ui_SysIPLabel,"IP ADDR: 192.168.1.145");
lv_obj_set_style_text_color(ui_SysIPLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SysIPLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SysIPLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SysAPIStatusLabel = lv_label_create(ui_ScreenSystem);
lv_obj_set_width( ui_SysAPIStatusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SysAPIStatusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SysAPIStatusLabel, 20 );
lv_obj_set_y( ui_SysAPIStatusLabel, 75 );
lv_label_set_text(ui_SysAPIStatusLabel,"API AUTH: SUCCESS (200)");
lv_obj_set_style_text_color(ui_SysAPIStatusLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SysAPIStatusLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SysAPIStatusLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SysHeapLabel = lv_label_create(ui_ScreenSystem);
lv_obj_set_width( ui_SysHeapLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SysHeapLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SysHeapLabel, 20 );
lv_obj_set_y( ui_SysHeapLabel, 95 );
lv_label_set_text(ui_SysHeapLabel,"FREE HEAP: 142 KB");
lv_obj_set_style_text_color(ui_SysHeapLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SysHeapLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SysHeapLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AlertNoticeBox = lv_obj_create(ui_ScreenSystem);
lv_obj_set_width( ui_AlertNoticeBox, 280);
lv_obj_set_height( ui_AlertNoticeBox, 95);
lv_obj_set_x( ui_AlertNoticeBox, 0 );
lv_obj_set_y( ui_AlertNoticeBox, -15 );
lv_obj_set_align( ui_AlertNoticeBox, LV_ALIGN_BOTTOM_MID );
lv_obj_remove_flag( ui_AlertNoticeBox, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AlertNoticeBox, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_AlertNoticeBox, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AlertNoticeBox, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_AlertNoticeBox, lv_color_hex(0xD0D0D0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_AlertNoticeBox, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_AlertNoticeBox, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_AlertNoticeBox, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_AlertNoticeBox, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_AlertNoticeBox, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_AlertNoticeBox, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AlertTextLabel = lv_label_create(ui_AlertNoticeBox);
lv_obj_set_width( ui_AlertTextLabel, 264);
lv_obj_set_height( ui_AlertTextLabel, 79);
lv_label_set_text(ui_AlertTextLabel,"No active route diversions. Traffic flowing normally along Ngau Tau Kok Road.");
lv_obj_set_style_text_color(ui_AlertTextLabel, lv_color_hex(0x555555), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AlertTextLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AlertTextLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BtnSystemBack, ui_event_BtnSystemBack, LV_EVENT_ALL, NULL);

}

void ui_ScreenSystem_screen_destroy(void)
{
   if (ui_ScreenSystem) lv_obj_del(ui_ScreenSystem);

// NULL screen variables
ui_ScreenSystem= NULL;
ui_SystemHeader= NULL;
ui_BtnSystemBack= NULL;
ui_BtnSystemBackLabel= NULL;
ui_SystemTitleLabel1= NULL;
ui_SysIPLabel= NULL;
ui_SysAPIStatusLabel= NULL;
ui_SysHeapLabel= NULL;
ui_AlertNoticeBox= NULL;
ui_AlertTextLabel= NULL;

}
