// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: BusStop852

#include "ui.h"

lv_obj_t *ui_ScreenMain = NULL;lv_obj_t *ui_HeaderPanel = NULL;lv_obj_t *ui_HeaderRouteLabel = NULL;lv_obj_t *ui_HeaderDestLabel = NULL;lv_obj_t *ui_HeaderNextLabel = NULL;lv_obj_t *ui_BusListContainer = NULL;lv_obj_t *ui_BusRow1 = NULL;lv_obj_t *ui_Route_Number_Label = NULL;lv_obj_t *ui_Destination_Label = NULL;lv_obj_t *ui_Station_Name_Label = NULL;lv_obj_t *ui_ETA_Countdown_Label = NULL;lv_obj_t *ui_Minutes_Unit_Label = NULL;lv_obj_t *ui_DividerLine = NULL;lv_obj_t *ui_BusRow2 = NULL;lv_obj_t *ui_Route_Number_Label1 = NULL;lv_obj_t *ui_Destination_Label1 = NULL;lv_obj_t *ui_Station_Name_Label1 = NULL;lv_obj_t *ui_ETA_Countdown_Label1 = NULL;lv_obj_t *ui_Minutes_Unit_Label1 = NULL;lv_obj_t *ui_DividerLine1 = NULL;lv_obj_t *ui_BusRow3 = NULL;lv_obj_t *ui_Route_Number_Label2 = NULL;lv_obj_t *ui_Destination_Label2 = NULL;lv_obj_t *ui_Station_Name_Label2 = NULL;lv_obj_t *ui_ETA_Countdown_Label2 = NULL;lv_obj_t *ui_Minutes_Unit_Label2 = NULL;lv_obj_t *ui_DividerLine2 = NULL;lv_obj_t *ui_BusRow4 = NULL;lv_obj_t *ui_Route_Number_Label3 = NULL;lv_obj_t *ui_Destination_Label3 = NULL;lv_obj_t *ui_Station_Name_Label3 = NULL;lv_obj_t *ui_ETA_Countdown_Label3 = NULL;lv_obj_t *ui_Minutes_Unit_Label3 = NULL;lv_obj_t *ui_DividerLine3 = NULL;lv_obj_t *ui_BusRow5 = NULL;lv_obj_t *ui_Route_Number_Label4 = NULL;lv_obj_t *ui_Destination_Label4 = NULL;lv_obj_t *ui_Station_Name_Label4 = NULL;lv_obj_t *ui_ETA_Countdown_Label4 = NULL;lv_obj_t *ui_Minutes_Unit_Label4 = NULL;lv_obj_t *ui_DividerLine4 = NULL;lv_obj_t *ui_StatusSidebar = NULL;lv_obj_t *ui_SidebarWeatherIcon = NULL;lv_obj_t *ui_SidebarTempLabel = NULL;lv_obj_t *ui_SidebarHumidLabel = NULL;lv_obj_t *ui_DividerLineSS = NULL;lv_obj_t *ui_SidebarClockLabel = NULL;lv_obj_t *ui_SidebarRSSILabel = NULL;lv_obj_t *ui_FooterPanel = NULL;lv_obj_t *ui_FooterWifiLabel = NULL;lv_obj_t *ui_FooterTimeLabel = NULL;
// event funtions
void ui_event_BusRow1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenDetail, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_ScreenDetail_screen_init);
}
}

void ui_event_SidebarClockLabel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenAlarm, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_ScreenAlarm_screen_init);
}
}

void ui_event_SidebarRSSILabel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSystem, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_ScreenSystem_screen_init);
}
}

void ui_event_FooterWifiLabel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenSystem, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0, &ui_ScreenSystem_screen_init);
}
}

// build funtions

void ui_ScreenMain_screen_init(void)
{
ui_ScreenMain = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenMain, lv_color_hex(0xF8F9FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenMain, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeaderPanel = lv_obj_create(ui_ScreenMain);
lv_obj_set_width( ui_HeaderPanel, 320);
lv_obj_set_height( ui_HeaderPanel, 24);
lv_obj_remove_flag( ui_HeaderPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeaderPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeaderPanel, lv_color_hex(0xE1251B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeaderPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_HeaderPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_HeaderPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_HeaderPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_HeaderPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_HeaderPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_HeaderPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeaderRouteLabel = lv_label_create(ui_HeaderPanel);
lv_obj_set_width( ui_HeaderRouteLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeaderRouteLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeaderRouteLabel, 10 );
lv_obj_set_y( ui_HeaderRouteLabel, 4 );
lv_label_set_text(ui_HeaderRouteLabel,"Route");

ui_HeaderDestLabel = lv_label_create(ui_HeaderPanel);
lv_obj_set_width( ui_HeaderDestLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeaderDestLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeaderDestLabel, 70 );
lv_obj_set_y( ui_HeaderDestLabel, 4 );
lv_label_set_text(ui_HeaderDestLabel,"Dest.");

ui_HeaderNextLabel = lv_label_create(ui_HeaderPanel);
lv_obj_set_width( ui_HeaderNextLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeaderNextLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeaderNextLabel, 170 );
lv_obj_set_y( ui_HeaderNextLabel, 4 );
lv_label_set_text(ui_HeaderNextLabel,"Next");

ui_BusListContainer = lv_obj_create(ui_ScreenMain);
lv_obj_set_width( ui_BusListContainer, 240);
lv_obj_set_height( ui_BusListContainer, 192);
lv_obj_set_x( ui_BusListContainer, 0 );
lv_obj_set_y( ui_BusListContainer, 24 );
lv_obj_set_flex_flow(ui_BusListContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_BusListContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_scrollbar_mode(ui_BusListContainer, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_BusListContainer, LV_DIR_VER);
lv_obj_set_style_bg_color(ui_BusListContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BusListContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_BusListContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_BusListContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_BusListContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_BusListContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_BusListContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_BusListContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BusRow1 = lv_obj_create(ui_BusListContainer);
lv_obj_set_width( ui_BusRow1, 320);
lv_obj_set_height( ui_BusRow1, 42);
lv_obj_remove_flag( ui_BusRow1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BusRow1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BusRow1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_BusRow1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_BusRow1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_BusRow1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_BusRow1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_BusRow1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_BusRow1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Route_Number_Label = lv_label_create(ui_BusRow1);
lv_obj_set_width( ui_Route_Number_Label, 55);
lv_obj_set_height( ui_Route_Number_Label, 32);
lv_obj_set_x( ui_Route_Number_Label, 10 );
lv_obj_set_y( ui_Route_Number_Label, 4 );
lv_label_set_text(ui_Route_Number_Label,"2A");
lv_obj_set_style_text_color(ui_Route_Number_Label, lv_color_hex(0xE1251B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Route_Number_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Route_Number_Label, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Destination_Label = lv_label_create(ui_BusRow1);
lv_obj_set_width( ui_Destination_Label, 120);
lv_obj_set_height( ui_Destination_Label, 16);
lv_obj_set_x( ui_Destination_Label, 70 );
lv_obj_set_y( ui_Destination_Label, 4 );
lv_label_set_text(ui_Destination_Label,">> 樂華");
lv_obj_set_style_text_color(ui_Destination_Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Destination_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Destination_Label, &ui_font_NotoSansTC_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Station_Name_Label = lv_label_create(ui_BusRow1);
lv_obj_set_width( ui_Station_Name_Label, 120);
lv_obj_set_height( ui_Station_Name_Label, 16);
lv_obj_set_x( ui_Station_Name_Label, 70 );
lv_obj_set_y( ui_Station_Name_Label, 24 );
lv_label_set_text(ui_Station_Name_Label,"淘大花園");
lv_obj_set_style_text_color(ui_Station_Name_Label, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Station_Name_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Station_Name_Label, &ui_font_NotoSansTC_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ETA_Countdown_Label = lv_label_create(ui_BusRow1);
lv_obj_set_width( ui_ETA_Countdown_Label, 45);
lv_obj_set_height( ui_ETA_Countdown_Label, 35);
lv_obj_set_x( ui_ETA_Countdown_Label, 150 );
lv_obj_set_y( ui_ETA_Countdown_Label, 2 );
lv_label_set_text(ui_ETA_Countdown_Label,"1");
lv_obj_set_style_text_color(ui_ETA_Countdown_Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ETA_Countdown_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ETA_Countdown_Label, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ETA_Countdown_Label, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Minutes_Unit_Label = lv_label_create(ui_BusRow1);
lv_obj_set_width( ui_Minutes_Unit_Label, 35);
lv_obj_set_height( ui_Minutes_Unit_Label, 18);
lv_obj_set_x( ui_Minutes_Unit_Label, 200 );
lv_obj_set_y( ui_Minutes_Unit_Label, 16 );
lv_label_set_text(ui_Minutes_Unit_Label,"分鐘");
lv_obj_set_style_text_color(ui_Minutes_Unit_Label, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Minutes_Unit_Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Minutes_Unit_Label, &ui_font_NotoSansTC_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DividerLine = lv_obj_create(ui_BusRow1);
lv_obj_set_width( ui_DividerLine, 220);
lv_obj_set_height( ui_DividerLine, 1);
lv_obj_set_x( ui_DividerLine, 10 );
lv_obj_set_y( ui_DividerLine, 41 );
lv_obj_remove_flag( ui_DividerLine, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DividerLine, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DividerLine, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BusRow2 = lv_obj_create(ui_BusListContainer);
lv_obj_set_width( ui_BusRow2, 320);
lv_obj_set_height( ui_BusRow2, 42);
lv_obj_remove_flag( ui_BusRow2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BusRow2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BusRow2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_BusRow2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_BusRow2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_BusRow2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_BusRow2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_BusRow2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_BusRow2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Route_Number_Label1 = lv_label_create(ui_BusRow2);
lv_obj_set_width( ui_Route_Number_Label1, 55);
lv_obj_set_height( ui_Route_Number_Label1, 32);
lv_obj_set_x( ui_Route_Number_Label1, 10 );
lv_obj_set_y( ui_Route_Number_Label1, 4 );
lv_label_set_text(ui_Route_Number_Label1,"2X");
lv_obj_set_style_text_color(ui_Route_Number_Label1, lv_color_hex(0xE1251B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Route_Number_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Route_Number_Label1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Destination_Label1 = lv_label_create(ui_BusRow2);
lv_obj_set_width( ui_Destination_Label1, 120);
lv_obj_set_height( ui_Destination_Label1, 16);
lv_obj_set_x( ui_Destination_Label1, 70 );
lv_obj_set_y( ui_Destination_Label1, 4 );
lv_label_set_text(ui_Destination_Label1,">> 彩福");
lv_obj_set_style_text_color(ui_Destination_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Destination_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Destination_Label1, &ui_font_NotoSansTC_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Station_Name_Label1 = lv_label_create(ui_BusRow2);
lv_obj_set_width( ui_Station_Name_Label1, 120);
lv_obj_set_height( ui_Station_Name_Label1, 16);
lv_obj_set_x( ui_Station_Name_Label1, 70 );
lv_obj_set_y( ui_Station_Name_Label1, 22 );
lv_label_set_text(ui_Station_Name_Label1,"淘大花園");
lv_obj_set_style_text_color(ui_Station_Name_Label1, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Station_Name_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Station_Name_Label1, &ui_font_NotoSansTC_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ETA_Countdown_Label1 = lv_label_create(ui_BusRow2);
lv_obj_set_width( ui_ETA_Countdown_Label1, 45);
lv_obj_set_height( ui_ETA_Countdown_Label1, 35);
lv_obj_set_x( ui_ETA_Countdown_Label1, 150 );
lv_obj_set_y( ui_ETA_Countdown_Label1, 2 );
lv_label_set_text(ui_ETA_Countdown_Label1,"1");
lv_obj_set_style_text_color(ui_ETA_Countdown_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ETA_Countdown_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ETA_Countdown_Label1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ETA_Countdown_Label1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Minutes_Unit_Label1 = lv_label_create(ui_BusRow2);
lv_obj_set_width( ui_Minutes_Unit_Label1, 35);
lv_obj_set_height( ui_Minutes_Unit_Label1, 18);
lv_obj_set_x( ui_Minutes_Unit_Label1, 200 );
lv_obj_set_y( ui_Minutes_Unit_Label1, 16 );
lv_label_set_text(ui_Minutes_Unit_Label1,"分鐘");
lv_obj_set_style_text_color(ui_Minutes_Unit_Label1, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Minutes_Unit_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Minutes_Unit_Label1, &ui_font_NotoSansTC_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DividerLine1 = lv_obj_create(ui_BusRow2);
lv_obj_set_width( ui_DividerLine1, 220);
lv_obj_set_height( ui_DividerLine1, 1);
lv_obj_set_x( ui_DividerLine1, 10 );
lv_obj_set_y( ui_DividerLine1, 41 );
lv_obj_remove_flag( ui_DividerLine1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DividerLine1, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DividerLine1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BusRow3 = lv_obj_create(ui_BusListContainer);
lv_obj_set_width( ui_BusRow3, 320);
lv_obj_set_height( ui_BusRow3, 42);
lv_obj_remove_flag( ui_BusRow3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BusRow3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BusRow3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_BusRow3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_BusRow3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_BusRow3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_BusRow3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_BusRow3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_BusRow3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Route_Number_Label2 = lv_label_create(ui_BusRow3);
lv_obj_set_width( ui_Route_Number_Label2, 55);
lv_obj_set_height( ui_Route_Number_Label2, 32);
lv_obj_set_x( ui_Route_Number_Label2, 10 );
lv_obj_set_y( ui_Route_Number_Label2, 4 );
lv_label_set_text(ui_Route_Number_Label2,"28");
lv_obj_set_style_text_color(ui_Route_Number_Label2, lv_color_hex(0xE1251B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Route_Number_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Route_Number_Label2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Destination_Label2 = lv_label_create(ui_BusRow3);
lv_obj_set_width( ui_Destination_Label2, 120);
lv_obj_set_height( ui_Destination_Label2, 16);
lv_obj_set_x( ui_Destination_Label2, 70 );
lv_obj_set_y( ui_Destination_Label2, 4 );
lv_label_set_text(ui_Destination_Label2,">> 樂華");
lv_obj_set_style_text_color(ui_Destination_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Destination_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Destination_Label2, &ui_font_NotoSansTC_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Station_Name_Label2 = lv_label_create(ui_BusRow3);
lv_obj_set_width( ui_Station_Name_Label2, 120);
lv_obj_set_height( ui_Station_Name_Label2, 16);
lv_obj_set_x( ui_Station_Name_Label2, 70 );
lv_obj_set_y( ui_Station_Name_Label2, 22 );
lv_label_set_text(ui_Station_Name_Label2,"淘大花園");
lv_obj_set_style_text_color(ui_Station_Name_Label2, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Station_Name_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Station_Name_Label2, &ui_font_NotoSansTC_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ETA_Countdown_Label2 = lv_label_create(ui_BusRow3);
lv_obj_set_width( ui_ETA_Countdown_Label2, 45);
lv_obj_set_height( ui_ETA_Countdown_Label2, 35);
lv_obj_set_x( ui_ETA_Countdown_Label2, 150 );
lv_obj_set_y( ui_ETA_Countdown_Label2, 2 );
lv_label_set_text(ui_ETA_Countdown_Label2,"1");
lv_obj_set_style_text_color(ui_ETA_Countdown_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ETA_Countdown_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ETA_Countdown_Label2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ETA_Countdown_Label2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Minutes_Unit_Label2 = lv_label_create(ui_BusRow3);
lv_obj_set_width( ui_Minutes_Unit_Label2, 35);
lv_obj_set_height( ui_Minutes_Unit_Label2, 18);
lv_obj_set_x( ui_Minutes_Unit_Label2, 200 );
lv_obj_set_y( ui_Minutes_Unit_Label2, 16 );
lv_label_set_text(ui_Minutes_Unit_Label2,"分鐘");
lv_obj_set_style_text_color(ui_Minutes_Unit_Label2, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Minutes_Unit_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Minutes_Unit_Label2, &ui_font_NotoSansTC_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DividerLine2 = lv_obj_create(ui_BusRow3);
lv_obj_set_width( ui_DividerLine2, 220);
lv_obj_set_height( ui_DividerLine2, 1);
lv_obj_set_x( ui_DividerLine2, 10 );
lv_obj_set_y( ui_DividerLine2, 41 );
lv_obj_remove_flag( ui_DividerLine2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DividerLine2, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DividerLine2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BusRow4 = lv_obj_create(ui_BusListContainer);
lv_obj_set_width( ui_BusRow4, 320);
lv_obj_set_height( ui_BusRow4, 42);
lv_obj_remove_flag( ui_BusRow4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BusRow4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BusRow4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_BusRow4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_BusRow4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_BusRow4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_BusRow4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_BusRow4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_BusRow4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Route_Number_Label3 = lv_label_create(ui_BusRow4);
lv_obj_set_width( ui_Route_Number_Label3, 55);
lv_obj_set_height( ui_Route_Number_Label3, 32);
lv_obj_set_x( ui_Route_Number_Label3, 10 );
lv_obj_set_y( ui_Route_Number_Label3, 4 );
lv_label_set_text(ui_Route_Number_Label3,"13D");
lv_obj_set_style_text_color(ui_Route_Number_Label3, lv_color_hex(0xE1251B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Route_Number_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Route_Number_Label3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Destination_Label3 = lv_label_create(ui_BusRow4);
lv_obj_set_width( ui_Destination_Label3, 120);
lv_obj_set_height( ui_Destination_Label3, 16);
lv_obj_set_x( ui_Destination_Label3, 70 );
lv_obj_set_y( ui_Destination_Label3, 4 );
lv_label_set_text(ui_Destination_Label3,">> 寶達");
lv_obj_set_style_text_color(ui_Destination_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Destination_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Destination_Label3, &ui_font_NotoSansTC_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Station_Name_Label3 = lv_label_create(ui_BusRow4);
lv_obj_set_width( ui_Station_Name_Label3, 120);
lv_obj_set_height( ui_Station_Name_Label3, 16);
lv_obj_set_x( ui_Station_Name_Label3, 70 );
lv_obj_set_y( ui_Station_Name_Label3, 22 );
lv_label_set_text(ui_Station_Name_Label3,"淘大花園");
lv_obj_set_style_text_color(ui_Station_Name_Label3, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Station_Name_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Station_Name_Label3, &ui_font_NotoSansTC_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ETA_Countdown_Label3 = lv_label_create(ui_BusRow4);
lv_obj_set_width( ui_ETA_Countdown_Label3, 45);
lv_obj_set_height( ui_ETA_Countdown_Label3, 35);
lv_obj_set_x( ui_ETA_Countdown_Label3, 150 );
lv_obj_set_y( ui_ETA_Countdown_Label3, 2 );
lv_label_set_text(ui_ETA_Countdown_Label3,"1");
lv_obj_set_style_text_color(ui_ETA_Countdown_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ETA_Countdown_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ETA_Countdown_Label3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ETA_Countdown_Label3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Minutes_Unit_Label3 = lv_label_create(ui_BusRow4);
lv_obj_set_width( ui_Minutes_Unit_Label3, 35);
lv_obj_set_height( ui_Minutes_Unit_Label3, 18);
lv_obj_set_x( ui_Minutes_Unit_Label3, 200 );
lv_obj_set_y( ui_Minutes_Unit_Label3, 16 );
lv_label_set_text(ui_Minutes_Unit_Label3,"分鐘");
lv_obj_set_style_text_color(ui_Minutes_Unit_Label3, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Minutes_Unit_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Minutes_Unit_Label3, &ui_font_NotoSansTC_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DividerLine3 = lv_obj_create(ui_BusRow4);
lv_obj_set_width( ui_DividerLine3, 220);
lv_obj_set_height( ui_DividerLine3, 1);
lv_obj_set_x( ui_DividerLine3, 10 );
lv_obj_set_y( ui_DividerLine3, 41 );
lv_obj_remove_flag( ui_DividerLine3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DividerLine3, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DividerLine3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BusRow5 = lv_obj_create(ui_BusListContainer);
lv_obj_set_width( ui_BusRow5, 320);
lv_obj_set_height( ui_BusRow5, 42);
lv_obj_remove_flag( ui_BusRow5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BusRow5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BusRow5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_BusRow5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_BusRow5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_BusRow5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_BusRow5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_BusRow5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_BusRow5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Route_Number_Label4 = lv_label_create(ui_BusRow5);
lv_obj_set_width( ui_Route_Number_Label4, 55);
lv_obj_set_height( ui_Route_Number_Label4, 32);
lv_obj_set_x( ui_Route_Number_Label4, 10 );
lv_obj_set_y( ui_Route_Number_Label4, 4 );
lv_label_set_text(ui_Route_Number_Label4,"6D");
lv_obj_set_style_text_color(ui_Route_Number_Label4, lv_color_hex(0xE1251B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Route_Number_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Route_Number_Label4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Destination_Label4 = lv_label_create(ui_BusRow5);
lv_obj_set_width( ui_Destination_Label4, 120);
lv_obj_set_height( ui_Destination_Label4, 16);
lv_obj_set_x( ui_Destination_Label4, 70 );
lv_obj_set_y( ui_Destination_Label4, 4 );
lv_label_set_text(ui_Destination_Label4,">> 牛頭角");
lv_obj_set_style_text_color(ui_Destination_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Destination_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Destination_Label4, &ui_font_NotoSansTC_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Station_Name_Label4 = lv_label_create(ui_BusRow5);
lv_obj_set_width( ui_Station_Name_Label4, 120);
lv_obj_set_height( ui_Station_Name_Label4, 16);
lv_obj_set_x( ui_Station_Name_Label4, 70 );
lv_obj_set_y( ui_Station_Name_Label4, 22 );
lv_label_set_text(ui_Station_Name_Label4,"淘大花園");
lv_obj_set_style_text_color(ui_Station_Name_Label4, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Station_Name_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Station_Name_Label4, &ui_font_NotoSansTC_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ETA_Countdown_Label4 = lv_label_create(ui_BusRow5);
lv_obj_set_width( ui_ETA_Countdown_Label4, 45);
lv_obj_set_height( ui_ETA_Countdown_Label4, 35);
lv_obj_set_x( ui_ETA_Countdown_Label4, 150 );
lv_obj_set_y( ui_ETA_Countdown_Label4, 2 );
lv_label_set_text(ui_ETA_Countdown_Label4,"1");
lv_obj_set_style_text_color(ui_ETA_Countdown_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ETA_Countdown_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ETA_Countdown_Label4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ETA_Countdown_Label4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Minutes_Unit_Label4 = lv_label_create(ui_BusRow5);
lv_obj_set_width( ui_Minutes_Unit_Label4, 35);
lv_obj_set_height( ui_Minutes_Unit_Label4, 18);
lv_obj_set_x( ui_Minutes_Unit_Label4, 200 );
lv_obj_set_y( ui_Minutes_Unit_Label4, 16 );
lv_label_set_text(ui_Minutes_Unit_Label4,"分鐘");
lv_obj_set_style_text_color(ui_Minutes_Unit_Label4, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Minutes_Unit_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Minutes_Unit_Label4, &ui_font_NotoSansTC_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DividerLine4 = lv_obj_create(ui_BusRow5);
lv_obj_set_width( ui_DividerLine4, 220);
lv_obj_set_height( ui_DividerLine4, 1);
lv_obj_set_x( ui_DividerLine4, 10 );
lv_obj_set_y( ui_DividerLine4, 41 );
lv_obj_remove_flag( ui_DividerLine4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DividerLine4, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DividerLine4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusSidebar = lv_obj_create(ui_ScreenMain);
lv_obj_set_width( ui_StatusSidebar, 80);
lv_obj_set_height( ui_StatusSidebar, 192);
lv_obj_set_x( ui_StatusSidebar, 240 );
lv_obj_set_y( ui_StatusSidebar, 24 );
lv_obj_remove_flag( ui_StatusSidebar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_StatusSidebar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StatusSidebar, lv_color_hex(0xEAEAEA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StatusSidebar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_StatusSidebar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_StatusSidebar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_StatusSidebar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_StatusSidebar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_StatusSidebar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_StatusSidebar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SidebarWeatherIcon = lv_image_create(ui_StatusSidebar);
lv_obj_set_width( ui_SidebarWeatherIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SidebarWeatherIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SidebarWeatherIcon, 0 );
lv_obj_set_y( ui_SidebarWeatherIcon, 15 );
lv_obj_set_align( ui_SidebarWeatherIcon, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_SidebarWeatherIcon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_remove_flag( ui_SidebarWeatherIcon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SidebarTempLabel = lv_label_create(ui_StatusSidebar);
lv_obj_set_width( ui_SidebarTempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SidebarTempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SidebarTempLabel, 0 );
lv_obj_set_y( ui_SidebarTempLabel, 50 );
lv_obj_set_align( ui_SidebarTempLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_SidebarTempLabel,"28°C");
lv_obj_set_style_text_color(ui_SidebarTempLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SidebarTempLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SidebarTempLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SidebarHumidLabel = lv_label_create(ui_StatusSidebar);
lv_obj_set_width( ui_SidebarHumidLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SidebarHumidLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SidebarHumidLabel, 0 );
lv_obj_set_y( ui_SidebarHumidLabel, 70 );
lv_obj_set_align( ui_SidebarHumidLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_SidebarHumidLabel,"82% RH");
lv_obj_set_style_text_color(ui_SidebarHumidLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SidebarHumidLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SidebarHumidLabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DividerLineSS = lv_obj_create(ui_StatusSidebar);
lv_obj_set_width( ui_DividerLineSS, 60);
lv_obj_set_height( ui_DividerLineSS, 1);
lv_obj_set_x( ui_DividerLineSS, 0 );
lv_obj_set_y( ui_DividerLineSS, 95 );
lv_obj_set_align( ui_DividerLineSS, LV_ALIGN_TOP_MID );
lv_obj_remove_flag( ui_DividerLineSS, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_DividerLineSS, lv_color_hex(0xD0D0D0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DividerLineSS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SidebarClockLabel = lv_label_create(ui_StatusSidebar);
lv_obj_set_width( ui_SidebarClockLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SidebarClockLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SidebarClockLabel, 0 );
lv_obj_set_y( ui_SidebarClockLabel, 90 );
lv_obj_set_align( ui_SidebarClockLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_SidebarClockLabel,"17:50");
lv_obj_add_flag( ui_SidebarClockLabel, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_SidebarClockLabel, lv_color_hex(0xE1251B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SidebarClockLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SidebarClockLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SidebarRSSILabel = lv_label_create(ui_StatusSidebar);
lv_obj_set_width( ui_SidebarRSSILabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SidebarRSSILabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SidebarRSSILabel, 0 );
lv_obj_set_y( ui_SidebarRSSILabel, -15 );
lv_obj_set_align( ui_SidebarRSSILabel, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_SidebarRSSILabel,"SIG: -65dB");
lv_obj_add_flag( ui_SidebarRSSILabel, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_SidebarRSSILabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SidebarRSSILabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SidebarRSSILabel, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FooterPanel = lv_obj_create(ui_ScreenMain);
lv_obj_set_width( ui_FooterPanel, 320);
lv_obj_set_height( ui_FooterPanel, 24);
lv_obj_set_x( ui_FooterPanel, 0 );
lv_obj_set_y( ui_FooterPanel, 216 );
lv_obj_remove_flag( ui_FooterPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_FooterPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_FooterPanel, lv_color_hex(0xE1251B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FooterPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_FooterPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_FooterPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_FooterPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_FooterPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_FooterPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_FooterPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FooterWifiLabel = lv_label_create(ui_FooterPanel);
lv_obj_set_width( ui_FooterWifiLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FooterWifiLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FooterWifiLabel, 10 );
lv_obj_set_y( ui_FooterWifiLabel, 4 );
lv_label_set_text(ui_FooterWifiLabel,"WiFi: CONNECTED");
lv_obj_add_flag( ui_FooterWifiLabel, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_color(ui_FooterWifiLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FooterWifiLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FooterWifiLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FooterTimeLabel = lv_label_create(ui_FooterPanel);
lv_obj_set_width( ui_FooterTimeLabel, 100);
lv_obj_set_height( ui_FooterTimeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FooterTimeLabel, 210 );
lv_obj_set_y( ui_FooterTimeLabel, 4 );
lv_label_set_text(ui_FooterTimeLabel,"Update: 16:50");
lv_obj_set_style_text_color(ui_FooterTimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FooterTimeLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_FooterTimeLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FooterTimeLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BusRow1, ui_event_BusRow1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SidebarClockLabel, ui_event_SidebarClockLabel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SidebarRSSILabel, ui_event_SidebarRSSILabel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FooterWifiLabel, ui_event_FooterWifiLabel, LV_EVENT_ALL, NULL);

}

void ui_ScreenMain_screen_destroy(void)
{
   if (ui_ScreenMain) lv_obj_del(ui_ScreenMain);

// NULL screen variables
ui_ScreenMain= NULL;
ui_HeaderPanel= NULL;
ui_HeaderRouteLabel= NULL;
ui_HeaderDestLabel= NULL;
ui_HeaderNextLabel= NULL;
ui_BusListContainer= NULL;
ui_BusRow1= NULL;
ui_Route_Number_Label= NULL;
ui_Destination_Label= NULL;
ui_Station_Name_Label= NULL;
ui_ETA_Countdown_Label= NULL;
ui_Minutes_Unit_Label= NULL;
ui_DividerLine= NULL;
ui_BusRow2= NULL;
ui_Route_Number_Label1= NULL;
ui_Destination_Label1= NULL;
ui_Station_Name_Label1= NULL;
ui_ETA_Countdown_Label1= NULL;
ui_Minutes_Unit_Label1= NULL;
ui_DividerLine1= NULL;
ui_BusRow3= NULL;
ui_Route_Number_Label2= NULL;
ui_Destination_Label2= NULL;
ui_Station_Name_Label2= NULL;
ui_ETA_Countdown_Label2= NULL;
ui_Minutes_Unit_Label2= NULL;
ui_DividerLine2= NULL;
ui_BusRow4= NULL;
ui_Route_Number_Label3= NULL;
ui_Destination_Label3= NULL;
ui_Station_Name_Label3= NULL;
ui_ETA_Countdown_Label3= NULL;
ui_Minutes_Unit_Label3= NULL;
ui_DividerLine3= NULL;
ui_BusRow5= NULL;
ui_Route_Number_Label4= NULL;
ui_Destination_Label4= NULL;
ui_Station_Name_Label4= NULL;
ui_ETA_Countdown_Label4= NULL;
ui_Minutes_Unit_Label4= NULL;
ui_DividerLine4= NULL;
ui_StatusSidebar= NULL;
ui_SidebarWeatherIcon= NULL;
ui_SidebarTempLabel= NULL;
ui_SidebarHumidLabel= NULL;
ui_DividerLineSS= NULL;
ui_SidebarClockLabel= NULL;
ui_SidebarRSSILabel= NULL;
ui_FooterPanel= NULL;
ui_FooterWifiLabel= NULL;
ui_FooterTimeLabel= NULL;

}
