// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: BusStop852

#include "ui.h"

lv_obj_t *ui_ScreenBoot = NULL;lv_obj_t *ui_SystemTitleLabel = NULL;lv_obj_t *ui_BootStatusLabel = NULL;lv_obj_t *ui_Spinner1 = NULL;
// event funtions
void ui_event_ScreenBoot( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_ScreenMain, LV_SCR_LOAD_ANIM_FADE_ON, 300, 3000, &ui_ScreenMain_screen_init);
}
}

// build funtions

void ui_ScreenBoot_screen_init(void)
{
ui_ScreenBoot = lv_obj_create(NULL);
lv_obj_remove_flag( ui_ScreenBoot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenBoot, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenBoot, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemTitleLabel = lv_label_create(ui_ScreenBoot);
lv_obj_set_width( ui_SystemTitleLabel, 280);
lv_obj_set_height( ui_SystemTitleLabel, 25);
lv_obj_set_x( ui_SystemTitleLabel, 0 );
lv_obj_set_y( ui_SystemTitleLabel, -40 );
lv_obj_set_align( ui_SystemTitleLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SystemTitleLabel,"BusStop852 v0.1");
lv_obj_set_style_text_color(ui_SystemTitleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SystemTitleLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SystemTitleLabel, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BootStatusLabel = lv_label_create(ui_ScreenBoot);
lv_obj_set_width( ui_BootStatusLabel, 280);
lv_obj_set_height( ui_BootStatusLabel, 20);
lv_obj_set_align( ui_BootStatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BootStatusLabel,"Connecting to Wi-Fi...");
lv_obj_set_style_text_color(ui_BootStatusLabel, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BootStatusLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BootStatusLabel, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Spinner1 = lv_spinner_create(ui_ScreenBoot);
//lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
lv_obj_set_width( ui_Spinner1, 30);
lv_obj_set_height( ui_Spinner1, 30);
lv_obj_set_x( ui_Spinner1, 0 );
lv_obj_set_y( ui_Spinner1, 45 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xE1251B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ScreenBoot, ui_event_ScreenBoot, LV_EVENT_ALL, NULL);

}

void ui_ScreenBoot_screen_destroy(void)
{
   if (ui_ScreenBoot) lv_obj_del(ui_ScreenBoot);

// NULL screen variables
ui_ScreenBoot= NULL;
ui_SystemTitleLabel= NULL;
ui_BootStatusLabel= NULL;
ui_Spinner1= NULL;

}
