// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: BusStop852

#ifndef UI_SCREENMAIN_H
#define UI_SCREENMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMain
extern void ui_ScreenMain_screen_init(void);
extern void ui_ScreenMain_screen_destroy(void);
extern lv_obj_t *ui_ScreenMain;
extern lv_obj_t *ui_HeaderPanel;
extern lv_obj_t *ui_HeaderRouteLabel;
extern lv_obj_t *ui_HeaderDestLabel;
extern lv_obj_t *ui_HeaderNextLabel;
extern lv_obj_t *ui_BusListContainer;
extern void ui_event_BusRow1( lv_event_t * e);
extern lv_obj_t *ui_BusRow1;
extern lv_obj_t *ui_Route_Number_Label;
extern lv_obj_t *ui_Destination_Label;
extern lv_obj_t *ui_Station_Name_Label;
extern lv_obj_t *ui_ETA_Countdown_Label;
extern lv_obj_t *ui_Minutes_Unit_Label;
extern lv_obj_t *ui_DividerLine;
extern lv_obj_t *ui_BusRow2;
extern lv_obj_t *ui_Route_Number_Label1;
extern lv_obj_t *ui_Destination_Label1;
extern lv_obj_t *ui_Station_Name_Label1;
extern lv_obj_t *ui_ETA_Countdown_Label1;
extern lv_obj_t *ui_Minutes_Unit_Label1;
extern lv_obj_t *ui_DividerLine1;
extern lv_obj_t *ui_BusRow3;
extern lv_obj_t *ui_Route_Number_Label2;
extern lv_obj_t *ui_Destination_Label2;
extern lv_obj_t *ui_Station_Name_Label2;
extern lv_obj_t *ui_ETA_Countdown_Label2;
extern lv_obj_t *ui_Minutes_Unit_Label2;
extern lv_obj_t *ui_DividerLine2;
extern lv_obj_t *ui_BusRow4;
extern lv_obj_t *ui_Route_Number_Label3;
extern lv_obj_t *ui_Destination_Label3;
extern lv_obj_t *ui_Station_Name_Label3;
extern lv_obj_t *ui_ETA_Countdown_Label3;
extern lv_obj_t *ui_Minutes_Unit_Label3;
extern lv_obj_t *ui_DividerLine3;
extern lv_obj_t *ui_BusRow5;
extern lv_obj_t *ui_Route_Number_Label4;
extern lv_obj_t *ui_Destination_Label4;
extern lv_obj_t *ui_Station_Name_Label4;
extern lv_obj_t *ui_ETA_Countdown_Label4;
extern lv_obj_t *ui_Minutes_Unit_Label4;
extern lv_obj_t *ui_DividerLine4;
extern lv_obj_t *ui_StatusSidebar;
extern lv_obj_t *ui_SidebarWeatherIcon;
extern lv_obj_t *ui_SidebarTempLabel;
extern lv_obj_t *ui_SidebarHumidLabel;
extern lv_obj_t *ui_DividerLineSS;
extern void ui_event_SidebarClockLabel( lv_event_t * e);
extern lv_obj_t *ui_SidebarClockLabel;
extern void ui_event_SidebarRSSILabel( lv_event_t * e);
extern lv_obj_t *ui_SidebarRSSILabel;
extern lv_obj_t *ui_FooterPanel;
extern void ui_event_FooterWifiLabel( lv_event_t * e);
extern lv_obj_t *ui_FooterWifiLabel;
extern lv_obj_t *ui_FooterTimeLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

