// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: BusStop852

#ifndef UI_SCREENSYSTEM_H
#define UI_SCREENSYSTEM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSystem
extern void ui_ScreenSystem_screen_init(void);
extern void ui_ScreenSystem_screen_destroy(void);
extern lv_obj_t *ui_ScreenSystem;
extern lv_obj_t *ui_SystemHeader;
extern void ui_event_BtnSystemBack( lv_event_t * e);
extern lv_obj_t *ui_BtnSystemBack;
extern lv_obj_t *ui_BtnSystemBackLabel;
extern lv_obj_t *ui_SystemTitleLabel1;
extern lv_obj_t *ui_SysIPLabel;
extern lv_obj_t *ui_SysAPIStatusLabel;
extern lv_obj_t *ui_SysHeapLabel;
extern lv_obj_t *ui_AlertNoticeBox;
extern lv_obj_t *ui_AlertTextLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

